const userData1 = [
  {
    id: 1,
    name: "John",
    email: "john@example.com",
    age: 30,
    city: "New York",
    state: "NY",
  },
  {
    id: 2,
    name: "Jane",
    email: "jane@example.com",
    age: 25,
    city: "Chicago",
    state: "IL",
  },
  {
    id: 3,
    name: "Bob",
    email: "bob@example.com",
    age: 35,
    city: "New York",
    state: "NY",
  },
  {
    id: 4,
    name: "Linda",
    email: "linda@example.com",
    age: 18,
    city: "New York",
    state: "NY",
  },
];

const userData2 = [
  {
    id: 1,
    name: "John",
    email: "john@example.com",
    age: 30,
    city: "New York",
    state: "NY",
  },
  {
    id: 2,
    name: "Jane",
    email: "jane@example.com",
    age: 25,
    city: "Chicago",
    state: "IL",
  },
  {
    id: 3,
    name: "Bob",
    email: "bob@example.com",
    age: 35,
    city: "New York",
    state: "NY",
  },
  {
    id: 4,
    name: "Linda",
    email: "linda@example.com",
    age: 18,
    city: "New York",
    state: "NY",
  },
  {
    id: 5,
    name: "Mila",
    email: "mila@example.com",
    age: 26,
    city: "California",
    state: "CA",
  },
  {
    id: 6,
    name: "Justin",
    email: "justin@example.com",
    age: 22,
    city: "Texas",
    state: "TX",
  },
  {
    id: 7,
    name: "Sean",
    email: "sean@example.com",
    age: 24,
    city: "California",
    state: "CA",
  },
  {
    id: 8,
    name: "Anne",
    email: "anne@example.com",
    age: 20,
    city: "Texas",
    state: "TX",
  },
  {
    id: 9,
    name: "Harry",
    email: "harry@example.com",
    age: 18,
    city: "California",
    state: "CA",
  },
];

export { userData1, userData2 };
